name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - OcelotWalrus
  - lumbar527
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please, before subminting any bug report, make sure you're using the latest plugin version and check if the bug still happen with the latest version
  - type: input
    id: bug-description
    attributes:
      label: Describe the bug
      description: Describe with the most words possible the bug that occurred.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To-Reproduce
      description: Write the steps to reproduce the behavior. You can add/remove existing steps.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what was supposed to happen instead of what happened to you.
      placeholder: ...
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add at least 1 to 3 screenshots if possible. It will help to understand more your problem.
      placeholder: ...
    validations:
      required: false
  - type: textarea
    id: game-logs
    attributes:
      label: Game Logs
      description: Drag & Drop your endless-sky logs file. It should be in your [endless-sky folder](https://github.com/endless-sky/endless-sky/wiki/CreatingPlugins) and it is called "errors.txt".
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: You can add additional context if you want.
      placeholder: ...
    validations:
      required: false
