blank_issues_enabled: false
contact_links:
  - name: Plugin Discussion & Support
    url: https://github.com/OcelotWalrus/Cromha-Expansion-plugin/discussions/1
    about: Please ask and answer questions here.
