name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["feature request"]
assignees:
  - OcelotWalrus
  - lumba527
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: is-related-to-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: ex. I'm always frustrated when [...].
    validations:
      required: false
  - type: input
    id: branch
    attributes:
      label: Feature branch
      description: Does you have a branch/repositor where you work on a solution for this issue?
      placeholder: ex. https://octocat/Cromha-Expansion-plugin/
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Solution you'd like
      description: A clear and concise description of what you want to happen or what you would like to add. You can add code blocks, screenshots or draws to explain yourself.
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: ...
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: You can add additional context if you want.
      placeholder: ...
    validations:
      required: false
