name: CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  
  cd_upload_artifacts_to_release:
    name: Upload
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install github-release
        run: |
          go install github.com/github-release/github-release@latest
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Create Zip
        run: |
          mkdir builds
          zip -r builds/Cromha-Expansion-plugin.zip data/ images/ plugins.txt icon.png LICENSE README.md copyright.txt
      - name: Create Tar
        run: |
          tar c -f builds/Cromha-Expansion-plugin.tar.gz data/ images/ icon.png LICENSE plugin.txt README.md copyright.txt
      - name: Set environment variables
        run: |
          echo "GITHUB_USER=$( echo ${{ github.repository }} | cut -d/ -f1 )" >> $GITHUB_ENV
          echo "GITHUB_REPO=$( echo ${{ github.repository }} | cut -d/ -f2 )" >> $GITHUB_ENV
      - name: Move/Create continuous tag
        run: |
          git tag --force 9.9.9-continuous ${{ github.sha }}
          git push --tags --force
      - name: Setup continuous release
        run: |
          DESCRIPTION="This is an automated build of the latest source triggered by commit ${{ github.sha }} (@${{ github.actor }}). It may be unstable or even crash, corrupt your save or eat your kitten. Use with caution!
            This release was made to be compatible with version 0.10.2 of Endless Sky.
             
            _Certain features will not work with earlier versions of Endless Sky._
            
            ### To use: 
             
            Download the compressed zip file and place the unzipped "Cromha-Expansion-plugin" folder in the appropriate location based on your system:
            * Windows: C:\Users\yourusername\AppData\Roaming\endless-sky\plugins
            * Mac OS X*: ~/Library/ApplicationSupport/endless-sky/plugins/
            * Linux: ~/.local/share/endless-sky/plugins/"
          if ! github-release info -t 9.9.9-continuous > /dev/null 2>&1; then
            github-release release \
              --tag 9.9.9-continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          else
            github-release edit \
              --tag 9.9.9-continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          fi
      - name: Add zip to release tag
        run: |
          github-release upload \
            --tag 9.9.9-continuous \
            --replace \
            --name Cromha-Expansion-plugin.zip \
            --file builds/Cromha-Expansion-plugin.zip
      - name: Add tar to release tag
        run: |
          github-release upload \
            --tag 9.9.9-continuous \
            --replace \
            --name Cromha-Expansion-plugin.tar.gz \
            --file builds/Cromha-Expansion-plugin.tar.gz
