name: CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  
  cd_upload_artifacts_to_release:
    name: Upload
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install github-release
        run: |
          go install github.com/github-release/github-release@latest
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Create Zip
        uses: vimtor/action-zip@v1
        with:
          files: data/ images/ about.txt icon.png README.md LICENSE copyright.txt
          dest: builds/Cromha-Expansion-plugin.zip
      - name: Create Tar
        uses: vimtor/action-zip@v1
        with:
          files: data/ images/ about.txt icon.png README.md LICENSE copyright.txt
          dest: builds/Cromha-Expansion-plugin.tar.gz
      - name: Set environment variables
        run: |
          echo "GITHUB_USER=$( echo ${{ github.repository }} | cut -d/ -f1 )" >> $GITHUB_ENV
          echo "GITHUB_REPO=$( echo ${{ github.repository }} | cut -d/ -f2 )" >> $GITHUB_ENV
      - name: Move/Create continuous tag
        run: |
          git tag --force continuous ${{ github.sha }}
          git push --tags --force
      - name: Setup continuous release
        run: |
          DESCRIPTION="Triggered on $(date -u '+%Y/%m/%d, %H:%M') UTC by commit ${{ github.sha }} (@${{ github.actor }})

          This is an automated build of the latest source. It may be unstable or even crash, corrupt your save or eat your kitten. Use with caution!

          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          if ! github-release info -t continuous > /dev/null 2>&1; then
            github-release release \
              --tag continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          else
            github-release edit \
              --tag continuous \
              --name "Continuous Build" \
              --description "$DESCRIPTION" \
              --pre-release
          fi
      - name: Add zip to release tag
        run: |
          github-release upload \
            --tag continuous \
            --replace \
            --name Cromha-Expansion-plugin.zip \
            --file builds/Cromha-Expansion-plugin.zip
      - name: Add tar to release tag
        run: |
          github-release upload \
            --tag continuous \
            --replace \
            --name Cromha-Expansion-plugin.tar.gz \
            --file builds/Cromha-Expansion-plugin.tar.gz

