---
name: Submodule Updates

#############################
# Start the job on all push #
#############################
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

###############
# Set the Job #
###############
jobs:
  submodule_update:
    name: Submodule update
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          git submodule update --remote
          git add -A
          git commit -m "Updated sub-modules"
          git push -u
      
