---
name: Submodule Updates

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

###############
# Set the Job #
###############
jobs:
  submodule:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
